// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxucasikopqtcztbgfbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4dWNhc2lrb3BxdGN6dGJnZmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwNjk5OTAsImV4cCI6MjEwNDY0NTk5MH0.B7-U_WoYi1xyRNUG6hCnHUxMaWun9GGLSon1vCvpaXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// IMPORTANT — mobile/PWA stability:
// supabase-js 2.95 defaults to `navigatorLock` (Web Locks API) in browsers.
// On mobile Chrome / Android WebView (the admin PWA), this lock occasionally
// gets orphaned after backgrounding, after which the Web Locks AbortController
// fires and surfaces as the very generic error "signal is aborted without
// reason" inside `signInWithPassword` / `getSession`. The user sees a sudden
// logout + a failed login retry.
//
// We provide an in-process lock (functionally identical to the auth-js
// `processLock`) so all auth ops are serialized within this tab WITHOUT
// touching navigator.locks. This removes the deadlock entirely while still
// preventing races between in-flight refresh/sign-in/sign-out calls.
const PROCESS_LOCKS: Record<string, Promise<unknown>> = {};
async function inProcessLock<R>(name: string, acquireTimeout: number, fn: () => Promise<R>): Promise<R> {
  const previous = PROCESS_LOCKS[name] ?? Promise.resolve();
  let timeoutHandle: ReturnType<typeof setTimeout> | null = null;
  const wait = Promise.race(
    [
      previous.catch(() => null),
      acquireTimeout >= 0
        ? new Promise<never>((_, reject) => {
            timeoutHandle = setTimeout(() => {
              const err: any = new Error(`Lock "${name}" acquisition timed out`);
              err.isAcquireTimeout = true;
              reject(err);
            }, acquireTimeout);
          })
        : null,
    ].filter(Boolean) as Promise<unknown>[]
  ).then(() => {
    if (timeoutHandle) clearTimeout(timeoutHandle);
    return fn();
  });

  PROCESS_LOCKS[name] = wait.catch(async (e: any) => {
    if (e && e.isAcquireTimeout) {
      // wait for the previous op to actually finish so the next caller is clean
      await previous.catch(() => null);
    }
    return null;
  });

  return wait;
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Disabled: the app's own AuthCallback/AdminOAuthCallback pages call
    // exchangeCodeForSession manually. Leaving this on races the client's
    // automatic exchange against that manual call for the same one-time
    // PKCE code, so the manual call always fails with a false "login failed" toast.
    detectSessionInUrl: false,
    flowType: 'pkce',
    lock: inProcessLock,
    lockAcquireTimeout: 15000,
  } as any,
});
